### ISSUE TITLE
1 of 4 regressions failing on mac os x 10.11.5 for rum 157d137

### ISSUE THREAD

**Issue by jmscott** [postgrespro/rum#2] opened 2016-06-26 21:30 UTC
1 of 4 regress tests fail for rum 157d137 under 9.6beta2 on mac os x.  failure appears to be a text columnar alignment issue in psql output.  details about build environment in attached zip file.

[regress-fail-157d137.zip](https://github.com/postgrespro/rum/files/333834/regress-fail-157d137.zip)

**Comment by select-artur** [comment] 2016-06-26 21:42
Hmm, strange. Thank you for the report. We will check it.

**Comment by jmscott** [comment] 2016-07-05 15:47
just tested on  linux 2.6.32-642.el6.x86_64.  got same regression fail 1/4 as described for mac in file regress-fail-157d137.zip.

**Comment by select-artur** [comment] 2016-07-05 20:23
Unfortunately I can't reproduce this bug.
I tested in Mac OS X 10.11.5 with en_US-UTF-8 locale and with CFLAGS:

-Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2

and nothing.
Also I tested in Arch Linux. The bug did not reproduced.

Can you build PostgreSQL and rum module without any special flags, run regression tests and send results? Thank you.

**Comment by jmscott** [comment] 2016-07-06 02:14
i built a private copy in $HOME/tmp as jmscott (not postgres).  failed in
same way.
i attached contents of entire contrib/rum directory, plus output of env,
pg_config and locale commands.

-j

**Comment by jmscott** [comment] 2016-07-06 17:36
let me verify that this regression ran against the isolated build of
postgresql.  i suspect the test may have run against the global 9.6beta2.

-j

**Comment by select-artur** [comment] 2016-07-06 19:15
It would be nice. I also tested on 10.10.5. And the bug did not reproduced.
After a while we will update the repository. Maybe the bug will gone.

**Comment by jmscott** [comment] 2016-07-07 04:13
i suspect something in my environment is causing the misaligned text in
psql output.  would be nice to know what.  probably be a day or so before i
can rebuild.

-j

**Comment by jmscott** [comment] 2016-07-11 13:56
i'll recompile early this week.  i got delayed due to the shootings in
dallas.  i live only a few blocks from dealey plaza where the shooter was
active, so things have been strange in my neighborhood, to say the least.

-j

**Comment by select-artur** [comment] 2016-07-11 14:07
Oh, of course. I heard this news.

**Comment by jmscott** [comment] 2016-07-18 05:18
ok,

after better isolating a full build script i am not able reproduce the
failed regression on either the mac or linux, so i'm going to assume the
earlier failure was due to something peculiar to my environment.
please close the issue.

i'll let you know if i can deduce the cause in my environment of the
earlier failure on both linux and mac.

sorry for the bother-j

**Comment by select-artur** [comment] 2016-07-19 21:41
Thank you for the issue. I close it.

**Closed by select-artur** 2016-07-19 21:41 UTC
