### ISSUE TITLE
invalid memory alloc request size

### ISSUE THREAD

**Issue by joseph-zh** [postgrespro/rum#51] opened 2018-12-06 09:53 UTC
HI:
  I use rum like this:
```
CREATE TABLE test_rum(t text, a tsvector);

CREATE TRIGGER tsvectorupdate
BEFORE UPDATE OR INSERT ON test_rum
FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger('a', 'pg_catalog.english', 't');

INSERT INTO test_rum(t) VALUES ('The situation is most beautiful');
INSERT INTO test_rum(t) VALUES ('It is a beautiful');
INSERT INTO test_rum(t) VALUES ('It looks like a beautiful place');
CREATE INDEX rumidx ON test_rum USING rum (a rum_tsvector_ops);
**TRUNCATE rumidx;
SELECT t from bttest ORDER BY id <=> to_tsquery('fdfdfafa');**
```
it well report a error like this
2018-12-06 17:47:22.060 CST [9345] ERROR:  invalid memory alloc request size 18446744073709478784
2018-12-06 17:47:22.060 CST [9345] STATEMENT:  SELECT t from test_rum ORDER BY a <=> to_tsquery('fdfdfafa');

**Comment by za-arthur** [comment] 2018-12-06 10:02
Hello,
Unfortunately I cannot reproduce the issue. Can you say how did you install RUM, version of RUM and version of PostgreSQL?
Also I don't fully understand your command here:
```
**TRUNCATE rumidx;
SELECT t from bttest ORDER BY id <=> to_tsquery('fdfdfafa');**
```

**Comment by joseph-zh** [comment] 2018-12-06 10:48
like this 
```
     set enable_seqscan = off;
     truncate test_rum;
     SELECT * from test_rum ORDER BY a <=> to_tsquery('fdfdfafa');
```
rum 1.2.0 and pg10.4

I write this sql conveniently, and find this error.

**Comment by za-arthur** [comment] 2018-12-06 10:59
Oh, I see. It seems there was a bug in 1.2.0. But now it should be fixed.
Please try 1.3.2 version.

**Comment by joseph-zh** [comment] 2018-12-06 11:14
OK,I well try. thanks.

**Closed** 2018-12-07 09:07 UTC
Labels: bug
