### ISSUE TITLE
Query plan depends on order direction

### ISSUE THREAD

**Issue by geoolekom** [postgrespro/rum#53] opened 2019-02-25 10:32 UTC
![default](https://user-images.githubusercontent.com/10210242/53331161-4791d180-3901-11e9-9432-6559a5b4a5f1.png)
![default](https://user-images.githubusercontent.com/10210242/53331191-5b3d3800-3901-11e9-845f-42f9c38ad60d.png)

But:
![default](https://user-images.githubusercontent.com/10210242/53331359-c25aec80-3901-11e9-92de-138ca7fcdbd7.png)
![default](https://user-images.githubusercontent.com/10210242/53331234-7740d980-3901-11e9-9304-2e6527d62dbc.png)

PostgreSQL 10.7, tried indices with rum_tsvector_hash_ops and rum_tsvector_ops
Is it a bug or am I doing it wrong?

**Comment by za-arthur** [comment] 2019-02-26 09:09
Hello,

Thank you for the issue. Unfortunately or happily it is not a bug.
When `RUM` index is created it is created in ascending order. PostgreSQL doesn't need additional sorting step in this case (your first query). But when you need the result in descending order PostgreSQL (1) gets items from the index and then (2) sorts items within additional step (`Sort` node in your second query).

**Comment by za-arthur** [comment] 2019-02-27 10:57
Do you have other questions? Should we close the issue?

**Closed** 2019-03-01 09:08 UTC
Labels: question
